### ISSUE TITLE
Failure on repeated builds

### ISSUE THREAD

**Issue by rkrzewski** [clempat/gulp-systemjs-resolver#11]
The resolver works great during first processing of scss sources, but when it is invoked from a `gulp.watch` for the second and consecutive time, it fails with the following exception:

```
TypeError: Incorrect configuration order. The baseURL must be configured with the first SystemJS.config call.
    at SystemJSNodeLoader.SystemJSLoader.config (/home/rafal/workspaces/web/gulp-jspm-sbt/node_modules/gulp-systemjs-resolver/node_modules/systemjs/dist/system.src.js:1753:13)
    at eval (eval at <anonymous> (/home/rafal/workspaces/web/gulp-jspm-sbt/node_modules/gulp-systemjs-resolver/index.js:26:11), <anonymous>:1:8)
    at module.exports (/home/rafal/workspaces/web/gulp-jspm-sbt/node_modules/gulp-systemjs-resolver/index.js:26:3)
    at Gulp.<anonymous> (/home/rafal/workspaces/web/gulp-jspm-sbt/gulpfile.js:110:13)
```

My test project is hosted on Bitbucket:  https://bitbucket.org/rkrzewski/gulp-jspm-sbt 

As far as I can tell, the problem arises because SystemJS is intialized on the first invocation of 
`eval(fs.readFileSync(options.systemConfig, 'utf8'));` and there is no obvious way to change or reset this configuration afterwards. A possible workaround would be introduced a guard variable that would ensure that SystemJS is initialized only once during `node` process lifetime. SystemJS config is not changed too often, so the requirement to restart resident gulp process to reload changes is not too onerous.

On the other hand, if there's something wrong with my gulpfile, I'm all ears :)

**Comment by clempat** [comment]
Thanks for your help !!

**Comment by rkrzewski** [comment]
You're welcome! How about tagging a new release? ;)

**Comment by clempat** [comment]
In the way :+1:
